const localProducts = [
  {
    id: 1,
    title: "유기농 제주 당근",
    price: 5000,
    description: "혈압 안정에 좋은 비타민 A가 풍부",
    origin: "제주 자연농원, 제주도",
    tags: ["New", "Organic"],
    image: require("./assets/images/dummy-img2.jpg"),
  },
  {
    id: 2,
    title: "GAP 인증 청송 사과",
    price: 8000,
    description: "항산화 성분이 풍부하여 피부 미용에 좋아요",
    origin: "청송 햇살농장, 경상북도 청송",
    tags: [],
    image: require("./assets/images/dummy-img2.jpg"),
  },
  {
    id: 3,
    title: "무농약 양배추",
    price: 6200,
    description: "위 건강에 좋은 식이섬유 다량 함유",
    origin: "초록들농장, 강원도 홍천",
    tags: ["Organic"],
    image: require("./assets/images/dummy-img2.jpg"),
  },
  {
    id: 4,
    title: "유기농 방울토마토",
    price: 4500,
    description: "리코펜이 풍부한 작은 건강 슈퍼푸드",
    origin: "맑은텃밭, 경기도 안성",
    tags: ["New", "Organic"],
    image: require("./assets/images/dummy-img2.jpg"),
  },
  {
    id: 5,
    title: "햇 고구마",
    price: 7000,
    description: "식이섬유와 천연 당분이 풍부",
    origin: "달콤농장, 전라남도 해남",
    tags: [],
    image: require("./assets/images/dummy-img2.jpg"),
  },
  {
    id: 6,
    title: "제철 딸기",
    price: 9800,
    description: "비타민 C 풍부, 입안 가득 달콤함",
    origin: "딸기사랑농원, 충청북도 음성",
    tags: ["New"],
    image: require("./assets/images/dummy-img2.jpg"),
  },
  {
    id: 7,
    title: "전통 재래 된장",
    price: 11000,
    description: "오래된 전통 방식으로 자연 발효",
    origin: "장인의 손맛, 전라북도 정읍",
    tags: [],
    image: require("./assets/images/dummy-img2.jpg"),
  },
  {
    id: 8,
    title: "친환경 콩나물",
    price: 3000,
    description: "아삭하고 신선한 아침 식탁의 필수",
    origin: "햇살농장, 경기도 여주",
    tags: ["Organic"],
    image: require("./assets/images/dummy-img2.jpg"),
  },
  {
    id: 9,
    title: "유기농 백미 4kg",
    price: 15000,
    description: "건강한 식탁의 시작, 부드러운 백미",
    origin: "청아한 논밭, 충청남도 당진",
    tags: [],
    image: require("./assets/images/dummy-img2.jpg"),
  },
  {
    id: 10,
    title: "발효 흑마늘즙",
    price: 12900,
    description: "면역력 강화에 좋은 건강 발효식품",
    origin: "흑마늘연구소, 경상남도 남해",
    tags: ["New"],
    image: require("./assets/images/dummy-img2.jpg"),
  },
];

export default localProducts;
